### PR TITLE
Update peerDependencies to support Grunt 1.0

### PR DESCRIPTION
**Pull request by gruntjs-updater**
Hello,

This is an automated issue request to update the `peerDependencies` for your Grunt plugin.
We ask you to merge this and **publish a new release on npm** to get your plugin working in Grunt 1.0!

Read more here: http://gruntjs.com/blog/2016-02-11-grunt-1.0.0-rc1-released#peer-dependencies
Also on Twitter: https://twitter.com/gruntjs/status/700819604155707392

If you have any questions or you no longer have time to maintain this plugin, then please let us know in this thread.

Thanks for creating and working on this plugin!

(P.S. Close this PR if it is a mistake, sorry)

### CODE REVIEW

**Comment by ChristianSchramm** [comment]
Please merge the pull request. thanks a lot

**Comment by ChristianSchramm** [comment]
Thank You very much, that was fast. But could you please publish the new release on npm? that would be great. :) I forget to mention.

**Comment by Manabu-GT** [comment]
Yes, I will do that today or tomorrow and let you know.

**Comment by Manabu-GT** [comment]
@ChristianSchramm now published as version 0.3.1. Thank you.

**Comment by ChristianSchramm** [comment]
Good work, thank you very much.

**Pull request merged**
