### PR TITLE
allow to use auto-install recursively

### PR DESCRIPTION
**Pull request by sieira**
This changes apply to [this feature request](https://github.com/Manabu-GT/grunt-auto-install/issues/10)

I'm a complete newbie to grunt so I didn't manage to add the required tests...

### CODE REVIEW

**Comment by sieira** [comment]
There you are. Just some considerations :

 1. When using the option "match", each component of the path to a folder has to match the regexps. For instance: `match: 'test'` will include `__basedir/test` and `__basedir/test/test1`, but not `__basedir/test/something`
 2. Using the `exclude` option will ignore any directory matching the regexps, and all it's subdirectories.
 3. This will fail when there are not package.json or bower.json file in the directory

I don't know if this is a proper behaviour (it applies for what I'm needing right now)

A different approach could be to get all the directories matching the regexps even if their parents don't (it may be more convenient), and ignore the excluded and all it's children.

By the way, since using this procedure for the installation is most likely done in a situation where front and backend are splitted, the auto-install should try to avoid running npm or bower if the package.json or the bower.json file are not in the directory instead of failing...

Just let me know how you prefer to do this

**Comment by sieira** [comment]
Sorry for flooding this thread. I adapted the feature to the behaviour mentioned above:

So now:
 * `recursive ` false by default activates/desactivates the recursive install process
 * `match` A regexp or a string of regexp which is a tautology by default, and tells the installer to perform the install on any directory whose name matching some pattern on the matching list regardless of the matching status of his parent
 * `exclude` A regexp or a string of regexp which is a contradiction by default, and tells the installer to ignore all the directories and it's subdirectories matching some pattern on the exclusion list.

**Comment by Manabu-GT** [comment]
:thumbsup:

**Comment by Manabu-GT** [comment]
After I fix some typos and two jshint errors I found, this will be released as v0.3.0.

Thank you.

**Comment by sieira** [comment]
Glad to have helped, thank you for the module too. : +1: )

**Pull request merged**
